cloudfoundry/diego-release

jobs/auctioneer/templates/auctioneer_ctl.erb, jobs/etcd/templates/etcd_ctl.erb, jobs/executor/templates/executor_ctl.erb, jobs/file_server/templates/file_server_ctl.erb, jobs/receptor/templates/receptor_ctl.erb, jobs/rep/templates/rep_ctl.erb, jobs/stager/templates/stager_ctl.erb, src/pid_utils.sh
[#88350400]
Signed-off-by: Matthew Sykes <matthew.sykes@gmail.com>
=> TCP tuning

config/blobs.yml, packages/windows_app_lifecycle/packaging, packages/windows_app_lifecycle/spec
Signed-off-by: John_Shahid <jshahid@pivotal.io>
=> Bump the windows app lifecycle

config/blobs.yml, packages/windows_app_lifecycle/packaging, packages/windows_app_lifecycle/spec
[#88945102]
Signed-off-by: Ben_Moss <bmoss@pivotal.io>
=> Bump windows app lifecycle

README.md
Closed the previous PR #52 and opened a new one.
=> Update README.md with link pointing to the correct location.

README.md, jobs/ssh_proxy/spec, jobs/ssh_proxy/templates/ssh_proxy_ctl.erb, manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego.yml, stubs-for-cf-release/enable_diego_ssh_in_cc.yml, stubs-for-cf-release/enable_diego_ssh_in_cf.yml
Configure UAA authentication for ssh-proxy
=> UAA configuration for ssh

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego.yml
Tracker story: [#108773546](https://www.pivotaltracker.com/story/show/108773546)
Signed-off-by: Nino Khodabandeh <nino.khodabandeh@hpe.com>
=> Enables TLS certs for metron

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego.yml
[#110117664]
Signed-off-by: Warren Fernandes <wfernandes@pivotal.io>
=> Adds enable_buffer and buffer_size properties to diego stubs.

scripts/deploy
because waiting is less fun than not waiting
=> add parallel blob download to deploy script

.gitmodules
These entries don't seem be to used anymore
Signed-off-by: John Shahid <jshahid@pivotal.io>
=> remove stale entries in .gitmodules

.gitmodules
diego-acceptance-tests was removed 5bce7bf5f0d61076c0ddd876bdaea3d113b9e742
=> Remove stale submodule from .gitmodules

jobs/ssh_proxy/spec, jobs/ssh_proxy/templates/ssh_proxy_ctl.erb
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>
=> add ssh-proxy properties for specifying allowed cipher,mac,kex algorithms

jobs/bbs/spec, jobs/bbs/templates/bbs_ctl.erb
Add a config value so the BBS advertise API can be configurable.
=> Make the BBS advertise address configurable

manifest-generation/misc-templates/vsphere-iaas-settings.yml
- this specifies the machine size for a vsphere environment
Signed-off-by: Can Berk Güder <cbguder@pivotal.io>
=> Add iaas-settings for vsphere

jobs/rep/templates/rep_ctl.erb
Signed-off-by: Fabio Berchtold <fabio.berchtold@swisscom.com>
=> export trusted_certs_flag to have it passed along to rep_as_vcap

docs/manifest-generation.md
cc @jaydunk
https://www.pivotaltracker.com/story/show/131119711
=> Add Container Networking flag info to docs

docs/manifest-generation.md
* The original double-slash line endings do not work when copying and pasting into a terminal (should be single-slash)
* The path to the mysql stub seems to have changed?
=> Fixup the example

docs/manifest-generation.md
- Add Netman to example
- Note that -N flag requires -g flag
cc @rosenhouse @rusha19
=> Update manifest generation docs

config/blobs.yml, packages/healthcheck/packaging, packages/windows_app_lifecycle/packaging, packages/windows_app_lifecycle/spec
=>  Compile Diego healthcheck for Windows

manifest-generation/disable-deprecated-bridge-jobs.yml, scripts/generate-deployment-manifest
[#133754911]
Signed-off-by: Zach Robinson <zrobinson@pivotal.io>
=> Fix how the "b" and "B" flags interact with eachother

jobs/rep_windows/templates/pre-start.ps1.erb
vsphere stmecells need to have explicit rule added for accessing rep on
listen_addr_securable.
[#137093839]
=> Add windows firewall rule for listen_addr_securable

manifest-generation/diego.yml, manifest-generation/disable-deprecated-bridge-jobs.yml
[#120643973]
Signed-off-by: Greg Cobb <gcobb@pivotal.io>
=> Manifest generation: -B flag disables tps_listener

docs/manifest-generation.md, manifest-generation/diego.yml, scripts/generate-deployment-manifest
Modifies manifest generation to accommodate renamed properties
@jaydunk @rusha19
https://www.pivotaltracker.com/story/show/137194915
=> Rename netman to cf-networking

CONTRIBUTING.md
Missing a space to make the header show up correctly.
=> Fix markdown in CONTRIBUTING doc

CONTRIBUTING.md
Update go version in the docs.
=> Update Go version in CONTRIBUTING.md

docs/migrating-from-consul-to-sql-locks.md, manifest-generation/diego.yml
[#143080755](https://www.pivotaltracker.com/story/show/143080755)
Signed-off-by: Luan Santos <lsantos@pivotal.io>
=> manifest gen supports add locket for tps watcher

manifest-generation/bosh-lite-stubs/postgres/diego-sql.yml
*note* do not merge before [this pr](https://github.com/cloudfoundry/cf-release/pull/1206) is merged into cf-release `release-candidate` branch
=> use the new locket database from cf-release

jobs/rep/spec
=> Clarify units for container metrics interval

jobs/bbs/templates/bbs.json.erb, jobs/benchmark-bbs/templates/benchmark.json.erb, jobs/locket/templates/locket.json.erb
Signed-off-by: Andrew Edstrom <aedstrom@pivotal.io>
=> Remove unused variables from json templates

jobs/ssh_proxy/spec, jobs/ssh_proxy/templates/ssh_proxy.json.erb
=> Configure ssh proxy idle connection timeout.

jobs/cfdot/spec, jobs/cfdot/templates/setup.erb
These are configurable in the other diego jobs, like auctioneer or rep, so should be configurable in cfdot as well.
=> Add API endpoint properties for cfdot job

jobs/rep/spec, jobs/rep/templates/rep.json.erb, jobs/rep_windows/spec, jobs/rep_windows/templates/rep.json.erb
[finishes #157675252](https://www.pivotaltracker.com/story/show/157675252)
Submodule src/code.cloudfoundry.org/executor 10c9efbf..9aefc559:
> Add a feature flag to disable unproxied port mappings.
Submodule src/code.cloudfoundry.org/rep 69da58fe..df7dff44:
> Add tests to ensure enable_unproxied_port_mappings is parsed properly
> Remove an incorrect comment
=> bump executor rep

jobs/rep/spec, jobs/rep/templates/rep.json.erb, jobs/rep_windows/spec, jobs/rep_windows/templates/rep.json.erb
This sets cpu shares proportional to memory
Please merge [this PR](https://github.com/cloudfoundry/executor/pull/33) before merging this one. Context is also in the other PR.
Co-authored-by: Ed King <eking@pivotal.io>
Co-authored-by: John Shahid <jshahid@pivotal.io>
=> Supply garden with CPU.Weight on container create

jobs/rep_windows/templates/drain.ps1.erb
Signed-off-by: Arjun Sreedharan <asreedharan@pivotal.io>
cc: @arjun024
=> Add logging for when drain script exits due to evacuation failure

config/blobs.yml
=> Bump envoy

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [3504d40f752eb5c20bc2883053547717bcb92fd8]("https://github.com/envoyproxy/envoy/commit/3504d40f752eb5c20bc2883053547717bcb92fd8") to [1a0363c885c2dbb1e48b03847dbd706d1ba43eba]("https://github.com/envoyproxy/envoy/commit/1a0363c885c2dbb1e48b03847dbd706d1ba43eba")
=> Bump envoy to 1a0363c885

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [1a0363c885c2dbb1e48b03847dbd706d1ba43eba]("https://github.com/envoyproxy/envoy/commit/1a0363c885c2dbb1e48b03847dbd706d1ba43eba") to [8fed4856a7cfe79cf60aa3682eff3ae55b231e49]("https://github.com/envoyproxy/envoy/commit/8fed4856a7cfe79cf60aa3682eff3ae55b231e49")
=> Bump envoy to 8fed4856a7

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [8fed4856a7cfe79cf60aa3682eff3ae55b231e49]("https://github.com/envoyproxy/envoy/commit/8fed4856a7cfe79cf60aa3682eff3ae55b231e49") to [923c4111bb48405ac96ef050c4f59ebbad3d7761]("https://github.com/envoyproxy/envoy/commit/923c4111bb48405ac96ef050c4f59ebbad3d7761")
=> Bump envoy to 923c4111bb

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [923c4111bb48405ac96ef050c4f59ebbad3d7761]("https://github.com/envoyproxy/envoy/commit/923c4111bb48405ac96ef050c4f59ebbad3d7761") to [fa0371e658658625bcf4eb48f9874b07a852404f]("https://github.com/envoyproxy/envoy/commit/fa0371e658658625bcf4eb48f9874b07a852404f")
=> Bump envoy to fa0371e658

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [fa0371e658658625bcf4eb48f9874b07a852404f]("https://github.com/envoyproxy/envoy/commit/fa0371e658658625bcf4eb48f9874b07a852404f") to [8fb3cb86082b17144a80402f5367ae65f06083bd-1.16.0]("https://github.com/envoyproxy/envoy/commit/8fb3cb86082b17144a80402f5367ae65f06083bd-1.16.0")
=> Bump envoy to 8fb3cb8608

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [8fb3cb86082b17144a80402f5367ae65f06083bd-1.16.0]("https://github.com/envoyproxy/envoy/commit/8fb3cb86082b17144a80402f5367ae65f06083bd-1.16.0") to [0717f49fef0dac3818cd7cdc52bf18e0ae1f7a2c-1.16.1]("https://github.com/envoyproxy/envoy/commit/0717f49fef0dac3818cd7cdc52bf18e0ae1f7a2c-1.16.1")
=> Bump envoy to 0717f49fef

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [bf5d0eb44b781ac26ff1513700bcb114b7cf4300-1.16.4]("https://github.com/envoyproxy/envoy/commit/bf5d0eb44b781ac26ff1513700bcb114b7cf4300-1.16.4") to [72ec3eed50b4154cb6d2251667b4c1c1ddfaa266-1.16.5]("https://github.com/envoyproxy/envoy/commit/72ec3eed50b4154cb6d2251667b4c1c1ddfaa266-1.16.5")
=> Bump envoy to 72ec3eed50

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [72ec3eed50b4154cb6d2251667b4c1c1ddfaa266-1.16.5]("https://github.com/envoyproxy/envoy/commit/72ec3eed50b4154cb6d2251667b4c1c1ddfaa266-1.16.5") to [a2a1e3eed4214a38608ec223859fcfa8fb679b14-1.19.1]("https://github.com/envoyproxy/envoy/commit/a2a1e3eed4214a38608ec223859fcfa8fb679b14-1.19.1")
=> Bump envoy to a2a1e3eed4

jobs/route_emitter/templates/route_emitter.json.erb, jobs/route_emitter_windows/templates/route_emitter.json.erb
https://github.com/cloudfoundry/diego-release/issues/609
Thank you!
=> Only use passwd auth if NATS requires it

jobs/route_emitter/templates/route_emitter.json.erb, jobs/route_emitter_windows/templates/route_emitter.json.erb
Signed-off-by: Geoff Franks <gfranks@vmware.com>
Signed-off-by: Amelia Downs <adowns@vmware.com>
Signed-off-by: Geoff Franks <gfranks@vmware.com>
Signed-off-by: Amelia Downs <adowns@vmware.com>
Signed-off-by: Geoff Franks <gfranks@vmware.com>
Signed-off-by: Amelia Downs <adowns@vmware.com>
> Please link the issue you created above for a bug or enhancement.
Thank you!
=> Fix leading zero check for route emitter's healthcheck_address

src/code.cloudfoundry.org/vendor/code.cloudfoundry.org/guardian/gqt/runner/runner.go
[Issue](https://github.com/cloudfoundry/diego-release/issues/629)
=> Replace GinkgoParallelNode with GinkgoParallelProcess

packages/certsplitter_windows/packaging, packages/healthcheck_windows/packaging, packages/rep_windows/packaging, packages/route_emitter_windows/packaging
> Please link the issue you created above for a bug or enhancement.
Thank you!
=> Add buildvcs=false to all windows package compilation
