cloudfoundry/diego-release

config/blobs.yml, packages/windows_app_lifecycle/packaging, packages/windows_app_lifecycle/spec
The new app lifecycle has lower case names for consistency with diego
[#91695280]
Signed-off-by: John_Shahid <jshahid@pivotal.io>
=> Update windows app lifecycle

README.md
The current bosh dance instructions have the unfortunate consequence that if you don't have a config/dev.yml and copy/paste it, Bosh will prompt you for the name of the release and receive the `bosh -n upload release` as the input. This fixes it so the prompt correctly waits for input.
=> Update bosh dance instructions

scripts/print-director-stub
If anyone wants to deploy to a bosh-lite that's not local, the `generate-bosh-lite-manifests` script will not work because it's hardcoded to look for the `uuid` of the director at `192.168.50.4`.
We parameterized this--with the default of `192.168.50.4`--to allow overrides but have no impact otherwise.
Signed-off-by: Shash Reddy <sreddy@pivotal.io>
=> Parameterize bosh-lite IP

manifest-generation/bosh-lite-stubs/property-overrides.yml
This is fine as long as you're using Garden-Linux-Release v0.306.0 or greater. It also makes performance on BOSH lite usable again!
=> Re-enable btrfs and disk quotas on BOSH lite

jobs/acceptance-tests/spec, jobs/acceptance-tests/templates/run.erb
Allow skipping of acceptance tests by using regex.
Porting from cf-release.
=> Allow skipping of acceptance tests by using regex

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego.yml
The template generation assumes that the cf install's consul isn't specifying the datacenter (simply using the default of `dc1`). This isn't true for our installation. This pull request allows the scripts to consume datacenter when present in the ingested cf manifest and defaults to `dc1` when not present.
=> Ability to set datacenter in templates (defaulting to "dc1")

jobs/acceptance-tests/spec, jobs/acceptance-tests/templates/run.erb
Default `-failFast` behaviour for **ginkgo** is annoying when you want to check each other test when a single one is failing.
I hope you will love this patch.
Appropriate patch for https://github.com/cloudfoundry-incubator/diego-acceptance-tests will be referred.
=> Added a variable to disable failfast

manifest-generation/examples/openstack/iaas-settings.yml
Hi guys,
this is `iaas-settings.yml` file to use with Openstack backend.
It is added because it's annoying to shrink bosh-lite one every time.
=> Added iaas settings for openstack

.gitmodules, packages/diego-sshd/spec
Adds necessary submodules for sftp and bumps diego-ssh and diego-acceptance tests.
Please see cloudfoundry-incubator/diego-ssh#15 and cloudfoundry-incubator/diego-acceptance-tests#4.
=> Add sftp subsystem to daemon

scripts/generate-acceptance-tests-manifest, scripts/generate-smoke-tests-manifest
Hi guys,
this is scripts to generate manifests for Smoke and Acceptance tests as long as main deployment manifest.
=> Added scripts to generate manifests for tests

.gitmodules, README.md
This is associated with cloudfoundry-incubator/diego-ssh#16. After removing the cli plugin from diego-ssh, we no longer need the cli source in our tree to build with.
This change can be applied after the diego-ssh submodule is bumped in diego-release.
=> Remove cloudfoundry/cli from diego tree

README.md
This is exceptionally confusing when you're trying to figure out what Diego version you should be using with your CF release.
=> Fix CF releases link that actually points to Diego releases

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego.yml
The loggregator team decided to change the TLS property names to more closely match the rest of CF.  This PR covers those name changes.
The corresponding story is [#112639903](https://www.pivotaltracker.com/story/show/112639903).
=> Update loggregator and metron properties to match latest loggregator

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego.yml
- Prepare for future addition of consul.agent.domain property
in consul-release that will not have a default value
[#115461031]
Signed-off-by: George Dean <gdean@pivotal.io>
=> Set consul.agent.domain property to cf.internal

manifest-generation/diego.yml
See cloudfoundry-incubator/etcd-release#9 for details and cloudfoundry/cf-release#928 for the matching change in `cf-release`. This really only applies after `etcd-release` has been bumped, but there should be no issues doing things out of order.
=> Update manifest template to have explicit etcd.advertise_urls_dns_suffix

src/pid_utils.sh
Not all environments allow writing to /proc/sys, allow these to be
controlled via config setting.
There is already a check for running_in_container() but this seems to be bosh-lite specific as it's looking for a specific entry in /proc/self/cgroup.
=> Add a switch to control writing to /proc/sys

examples/aws/README.md
In the beginning of the document we create folder DEPLOYMENT_DIR but there were couple of places with DEPLOYMENTS_DIR instead of DEPLOYMENT_DIR.
=> Fix folder names in README.md

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego-vizzini.yml, manifest-generation/diego.yml
We are planning to remove support for non-ssl mode in consul. We've updated the spiff templates in cf-release to reflect that certs and keys need to be provided and require_ssl is no longer needed (see: https://github.com/cloudfoundry/cf-release/commit/86152769da8fb1b62386bf645087df360e312885, https://github.com/cloudfoundry/cf-release/commit/93beb219f7b3f25d28e4cd1ce7cea56fa243e0f0, and https://github.com/cloudfoundry/cf-release/commit/301b8ab2cfccb931cd74e5b99ba5fa9a41532b71).
=> Require consul certs and keys from cf manifest

examples/aws/README.md
While following the AWS guide, we ran into issues with the fingerprint which was generated. The guide currently creates a `SHA256` fingerprint, and this pull request changes the `ssh-keygen` command to generate an `md5` fingerprint.
Without this change we were getting the following error message while attempting to SSH into an app deployed onto our CF installation.
```
○ → cf ssh dora -i 0
FAILED
Error opening SSH connection: ssh: handshake failed: Unsupported host key fingerprint format
```
As well as the following acceptance-tests failues
```
[Fail] {NO_DEA_SUPPORT} SSH ssh [It] can execute a remote command in the container
/Users/pivotal/go/src/github.com/cloudfoundry/cf-acceptance-tests/ssh/ssh_test.go:68
[Fail] {NO_DEA_SUPPORT} SSH ssh [It] runs an interactive session when no command …
```
=> Update fingerprint generation command

jobs/rep/spec, jobs/rep/templates/rep_ctl.erb, manifest-generation/bosh-lite-stubs/experimental/voldriver/drivers.yml, manifest-generation/bosh-lite-stubs/property-overrides.yml, manifest-generation/diego.yml, scripts/generate-bosh-lite-manifests, scripts/generate-deployment-manifest
-  Added stub for volman drivers in  `manifest-generation/bosh-lite-stubs/experimental/voldriver/`
- Modified diego.yml to include tags for spiff merging the voldrivers and their bosh-releases
- Modified scripts for manifest generation to include an optional driver colocated with the cell
[#112362783](https://www.pivotaltracker.com/story/show/112362783)
Signed-off-by: Nagapramod Mandagere <pramod@us.ibm.com>
Signed-off-by: Julian Hjortshoj <julian.hjortshoj@emc.com>
=> Volman driver can be colocated on the Cell

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego.yml
[#121255441]
Signed-off-by: Sam Nelson <snelson@pivotal.io>
=> Adds metron properties for communicating with CF ETCD over TLS

manifest-generation/diego.yml, manifest-generation/examples/openstack/iaas-settings.yml
Hi there!
In many cases we want to have a quite simple deployment in one single AZ. However, we have to keep descriptions for all resource pools and all 3 subnets in the manifest stub. This makes the stub file overloaded and looks dirty. Otherwise manifest generation script does not work.
This PR adds a few fixes into `diego.yml`, which makes it possible to keep stub file as clean as possible.
=> Shrink unused subnets

manifest-generation/garden-runc-properties.yml, scripts/generate-deployment-manifest
- Spiff didn't know where to find release_versions in garden-runc-properties,
so we had to merge it.
- The spiff merge order in manifest generation was in the wrong order
for garden-runc-properties to inherit the proper properties.
[#129105083] Garden runc deploy version should be update from the compatibility metrics from Diego.
Signed-off-by: Derek Reeve <dreeve@pivotal.io>
=> Fix template generation for garden-runc versions

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego-windows.yml, manifest-generation/diego.yml
These properties have been deprecated for quite some time, and we're removing them from diego and cf in preparation for removing them from loggregator.
[#117777293]
Signed-off-by: Jeremy Alvis <jalvis@pivotal.io>
=> Remove old loggregator properties

manifest-generation/config-from-cf-internal.yml, manifest-generation/config-from-cf.yml, manifest-generation/diego.yml
Hi Diego team
Container networking team PR to do the following:
- netman pulls etcd properties from config_from_cf
- remove unused cf_etcd section
Please let us know if you have any questions or concerns.
For more information, please see
https://www.pivotaltracker.com/story/show/131579069
Thanks
@markstgodard && @karampok
Container Networking Team
=> Netman inherits its etcd configuration from CF etcd

scripts/generate-windows-cell-deployment-manifest
* add a ':' so that the argument value is captured
=> Fix version override in windows cell manifest gen

manifest-generation/diego-windows.yml
Latest cf-release release-candidate has both windows jobs.
- metron_agent_windows
- consul_agent_windows
[#133772873](https://www.pivotaltracker.com/story/show/133772873)
=> Pull windows job from CF instead of garden-windows

jobs/rep_windows/monit, jobs/rep_windows/spec
A/C: As an operator I should be able to see logs from `rep_windows` in
syslog destination `syslog_daemon_config` defined in my cf manifest.
The support for the new environment variables has been added to AWS stemcell version `0.0.73` and above. 
[#133698951]
https://www.pivotaltracker.com/story/show/133698951
Signed-off-by: Natalie Arellano <narellano@pivotal.io>
=> Add syslog for rep_windows job

jobs/rep/templates/rep_as_vcap.erb
for other clouds that may have stealth firewalls.  
We have a case of where a vSphere environment answers on this address and hangs, causing rep race conditions to occur and the Diego cells never to come up.   
This fixes https://www.pivotaltracker.com/story/show/132794513
=> Timeout Azure metadata query after 5 seconds

docs/data-stores.md
The Logfile was erroneously used as "/var/vcap/sys/log/bbs/bbs.stdout" instead of "/var/vcap/sys/log/bbs/bbs.stdout.log" leading to the script failing when executing.
=> Updating the name of the bbs log file

docs/data-stores.md
Reverts cloudfoundry/diego-release#229
=> Revert "Updating the name of the bbs log file"

config/blobs.yml, packages/diego-sshd/packaging, packages/windows_app_lifecycle/packaging, packages/windows_app_lifecycle/spec
Instead of the submoduling the `diego-release` in [`windows_app_lifecycle`](https://github.com/cloudfoundry/windows_app_lifecycle) we
can inject the `diego-sshd` in the packaging script instead. This way we are in-sync with the upstream changes.
[#135953721]
=> Use diego-sshd package for windows_app_lifecycle

jobs/rep_windows/monit, jobs/rep_windows/spec, jobs/rep_windows/templates/start.ps1.erb
This PR removes the unnecessary powershell start script for rep.exe, as per [this story](https://www.pivotaltracker.com/story/show/134103211) and [this old PR](https://github.com/cloudfoundry/diego-release/pull/225)
=> Run rep.exe directly, no powershell start script

jobs/rep/spec, jobs/rep/templates/consul_ca.crt.erb, jobs/rep/templates/consul_client.crt.erb, jobs/rep/templates/consul_client.key.erb, jobs/rep/templates/rep.json.erb, jobs/rep_windows/spec, jobs/rep_windows/templates/consul_ca.crt.erb, jobs/rep_windows/templates/consul_client.crt.erb, jobs/rep_windows/templates/consul_client.key.erb, jobs/rep_windows/templates/rep.json.erb, manifest-generation/diego-windows.yml
This makes it possible to secure the local consul API.
Note that this depends on the corresponding functionality of consul-release that has been merged to develop (but not yet released.)
=> Add require_tls property to rep and rep_windows

jobs/rep/templates/trusted_certs.crt.erb
When adding certificates with diego.rep.trusted_certs the first certificate gets a prefix of two spaces rendering it invalid. This should fix it.
=> Bugfix diego.rep.trusted_certs leading two spaces in first certificate

examples/aws/README.md, examples/aws/deploy_aws_environment, examples/aws/stubs/cf/properties.yml, examples/aws/templates/cf/stub-internal.yml, examples/aws/templates/cf/stub.yml, scripts/generate-diego-certs
This enables the use case where Cloud Controller passes in HTTPS urls
for task callbacks that require mututal tls.
In that scenario, the CA that signs both diego and cloud controller
certificates have to be the same, this commit allows that CA to be
passed in as an argument.
Also, adds documentation to examples/aws/README.md as to how to deploy a
Diego cluster with this enabled.
Signed-off-by: Eric Promislow <eric.promislow@gmail.com>
=> Allow CA overriding when generating mutual TLS certs

examples/aws/templates/diego/property-overrides.yml, manifest-generation/bosh-lite-stubs/property-overrides.yml, manifest-generation/diego.yml
Add manifest generation to allow tps to configure mtls certs to use when communicating with CC
=> TPS-watcher uses mTLS to talk to CC

examples/aws/README.md, examples/aws/deploy_aws_environment, examples/aws/stubs/cf/properties.yml, examples/aws/templates/cf/stub-internal.yml, examples/aws/templates/cf/stub.yml, scripts/generate-diego-certs, scripts/generate-tps-certs
=> Tps watcher cert generation

examples/aws/README.md
as stated one sentence before, BOSH_DEPLOYMENT_DIR should be used
=> wrong env variable when deploy_aws_environment

jobs/rep_windows/spec, jobs/rep_windows/templates/ca_certs_for_downloads.crt.erb
This is required to enable SSL cert verification with custom CA certs. Currently custom certificates do not work in Windows cells because of the missing line this PR adds.
=> Use ca_certs_for_downloads in rep_windows

jobs/ssh_proxy/spec
This effectively no-ops if no one consumes the link on the other side, but enable link consumption by the HAProxy on cf-release and avoids using consul templating.
=> ssh_proxy provides conn link to be used by ha_proxy

manifest-generation/diego.yml
Garden runC does not set the privileged image plugin flags if the `garden.privileged_image_plugin` BOSH property is not set.
=> Use garden.privileged_image_plugin if GrootFS is enabled

docs/manifest-generation.md
GrootFS requires Cloud Foundry stacks to be provided as a path to a tarball rather than a path to a directory.
=> Add note on GrootFS and stacks

manifest-generation/bosh-lite-stubs/property-overrides.yml, manifest-generation/diego.yml, scripts/generate-cc-uploader-certs, scripts/generate-diego-certs
The following properties will be required for CC-Uploader as of the next
CAPI release:
- capi.cc_uploader.cc.ca_cert
- capi.cc_uploader.cc.client_cert
- capi.cc_uploader.cc.client_key
Signed-off-by: Lyle Franklin <lfranklin@pivotal.io>
[#139996781]
=> Add CC-Uploader certs for mutual TLS with CC

docs/tls-configuration.md
The links had incorrect paths and resulted in 404s.  We have replaced them with absolute paths.
=> Fix links to cert generation scripts

manifest-generation/diego.yml
In order to update the vcap password or to avoid root password from being modified the resource pools must be configurable with the `env.bosh` property.
/cc @suhlig
=> Allow env property in diego.yml to be merged

docs/manifest-generation.md, manifest-generation/diego.yml
This updates diego manifest generation to use new container networking jobs that are currently on cf-networking-release develop and will be in the next release.
Also added this note about property change-- let me know if you want different wording/if it makes sense:
**Note**: If you are deploying with ETCD, you will need to add the `bbs_overrides.job_properties.consul` to
`cf_networking_overrides.bbs_consul_properties`, as `cf_networking_overrides.bbs_consul_properties` will clobber any other values in that field.
[#144116673]
=> Update diego manifest generation to use new networking jobs

manifest-generation/diego.yml
This is just change the base spiff template diego.yml
So user can provide stub to override/add isolation segments tag
=> Add placement tag override on base template

docs/instance-identity.md
The current path is incorrect.
```
$ cf ssh proxy -c 'echo $CF_INSTANCE_CERT $CF_INSTANCE_KEY'
/etc/cf-instance-credentials/instance.crt /etc/cf-instance-credentials/instance.key
```
Cheers,
Angela and Gabe
=> Update path to container cert and key.

jobs/rep_windows/templates/pre-start.ps1.erb
This is so an unprivileged user in a container can read and execute buildpack / lifecycle binaries from the executor_cache
The change is compatible with garden-windows 2012 and 2016 as we are only adding permissions to the cache directory
=> Give BUILTIN/Users ReadAndExecute permission

manifest-generation/bosh-lite-stubs/property-overrides.yml, manifest-generation/diego.yml
[#149285861]
Fixed #335
Removed following unused properties
- diego.executor.drain_timeout_in_seconds
- diego.executor.log_level
=> Removed unused properties

manifest-generation/diego.yml
This is to allow different bbs `instance groups` to provide a different `named link`.
see: https://github.com/cloudfoundry-incubator/cf-networking-release/commit/b91dbac3c137a732adab0f2805d17627dd4001e0
=> Allow a way to configure each bbs template

jobs/rep_windows/spec, jobs/rep_windows/templates/pre-start.ps1.erb
This PR supports instance identity credentials on windows2016. This does not enable it on windows2012R2 (it is a no-op for this platform) as bind mounts do not work on windows2012R2 in the same way as linux or windows2016.
- Add instance identity certs to rep_windows templates
- Create instance identity directory in executor data directory
=> add ability to configure instance_identity on Windows

packages/auctioneer/spec, packages/bbs/spec, packages/benchmark-bbs/spec, packages/locket/spec, packages/rep/spec, packages/rep_windows/spec
Promotes value metrics to container metrics when appropriate.
[#150906690]
Signed-off-by: Wesley Jeanette <wjeanette@pivotal.io>
=> Bump go loggregator to v4.0.1

manifest-generation/diego.yml
[Apparently](https://lists.cloudfoundry.org/archives/list/cf-dev@lists.cloudfoundry.org/thread/5RDAQPM3LUXYYQLRZ7L6W5ZHZIUXNZJB/) the route-emitter is now on the hook to register TCP routes for app instances, even in "legacy" global mode. This change allows it to opt into that mode via the same property-overrides that configure the local route-emitters.
=> Enable global route-emitter to register TCP routes

config/blobs.yml, packages/buildpack_app_lifecycle/packaging, packages/diego-sshd/packaging, packages/diego-sshd/spec, packages/windows_app_lifecycle/packaging
- Add .tgz blob containing winpty.dll and winpty-agent.exe. These files
were extracted from: https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msvc2015.zip
- Update build flags to reflect changes in diego-ssh
[#150808829]
=> windows2016 supports cf ssh

packages/buildpack_app_lifecycle/spec, packages/windows_app_lifecycle/spec, scripts/sync-package-specs
Also update package specs and ensure package specs updated for
windows_app_lifecycle
Submodule src/code.cloudfoundry.org/buildpackapplifecycle 6a12719..80aa8b7:
> Always set DATABASE_URL from VCAP_SERVICES
> Builder interpolates VCAP_SERVICES & sets DATABASE_URL
> Remove VCAP_PLATFORM_OPTIONS from process env
> Locate certs relative to USERPROFILE on Windows 2012R2
> Path to CA certs is now passed via CF_SYSTEM_CERTS_PATH env var
> Put profile.d scripts outside of the app directory
> Determine DATABASE_URL from VCAP_SERVICES if unset
> VCAP_SERVICES interpolation uses TLS
> Launcher interpolates credhub-refs in VCAP_SERVICES
=> bump buildpackapplifecycle

jobs/auctioneer/templates/bpm.yml.erb, jobs/bbs/templates/bbs_ctl.erb, jobs/bbs/templates/bpm.yml.erb, jobs/file_server/templates/bpm.yml.erb, jobs/locket/templates/bpm.yml.erb, jobs/locket/templates/locket_ctl.erb, jobs/rep/spec, jobs/rep/templates/bpm-pre-start.erb, jobs/rep/templates/bpm.yml.erb, jobs/rep/templates/mount_instance_identity.erb, jobs/rep/templates/rep_ctl.erb, jobs/route_emitter/templates/bpm.yml.erb, jobs/ssh_proxy/templates/bpm.yml.erb
*Note*: This PR should **NOT** be merged until BPM version `0.2.0` is on [release-candidate of cf-deployment](https://github.com/cloudfoundry/cf-deployment/blob/release-candidate/operations/experimental/enable-bpm.yml#L8)
This change set entails all the configuration changes necessary to migrate from BPM v0.1.0 to v0.2.0.
Configuration changes include:
- [Environment variables as a hash](https://www.pivotaltracker.com/story/show/151345092)
- [Processes as an array](https://www.pivotaltracker.com/story/show/151451341)
- [Volumes are read only by default](https://www.pivotaltracker.com/story/show/151408169)
- [Rename Volumes to AdditionalVolumes](https://www.pivotaltracker.com/story/show/151531845)
- [Opting into persistent volumes being …
=> Update BPM to 0.2.0

docs/tls-configuration.md
Hi,
Currently both `database` and `cell` jobs are having similar certificate paths. With `path` I mean something like `properties.tls.cert`. This is confusing, because in theory you could have under the `properties` block the same path(`properties.tls.cert`) and I´m not sure which job will take it(`database` or `cell`). Seems the best way to define them, its always inside the `job` itself.
Therefore I modified the description to be more explicit in relation to where those certs should be defined, and in which spec file their description can be found. 
Regards,
Enrique Encalada
=> Improve tls notes documentation

packages/buildpack_app_lifecycle/packaging, packages/buildpack_app_lifecycle/spec, packages/windows_app_lifecycle/packaging, packages/windows_app_lifecycle/spec, scripts/sync-package-specs
Fixes an issue on Windows with env variables containing newline(s).
This PR must come after the BAL submodule is bumped to [this commit](https://github.com/cloudfoundry/buildpackapplifecycle/commit/1e1fa5ae3fdb39bf974fe111ce2e7373473550fc)
=> Add getenv binary to BAL and WAL.

.gitmodules, jobs/auctioneer/templates/auctioneer.json.erb, jobs/bbs/templates/bbs.json.erb, jobs/file_server/templates/file_server.json.erb, jobs/locket/templates/locket.json.erb, jobs/rep/templates/rep.json.erb, jobs/rep_windows/templates/rep.json.erb, jobs/route_emitter/templates/route_emitter.json.erb, jobs/route_emitter_windows/templates/route_emitter.json.erb, jobs/ssh_proxy/templates/ssh_proxy.json.erb, packages/auctioneer/spec, packages/bbs/spec, packages/benchmark-bbs/spec, packages/cfdot/spec, packages/diego-sshd/spec, packages/file_server/spec, packages/locket/spec, packages/rep/spec, packages/rep_windows/spec, packages/route_emitter/spec, packages/route_emitter_windows/spec, packages/ssh_proxy/spec
- Upgraded go-loggregator
- Add go-diodes which is a new dependency of go-loggregator
- Enables use of guids for instance IDs
This is meant as an updated PR following [this discussion](https://github.com/cloudfoundry/diego-release/pull/385). The submodule SHAs are included as a means to identify all submodules we also PR'd. Due to a bumped bbs submodule, there is a merge conflict here, but as we assumed the submodule PRs will get merged independently, the SHAs will probably change.
[#156379950]
=> Add source ID and instance ID to component configs

jobs/route_emitter/spec, jobs/route_emitter_windows/spec
Corrects C&P description for route_emitter health_check address
=> Correct route_emitter health check address description

jobs/rep/templates/bpm.yml.erb
- additional directories are needed for volman to discover CSI volume plugins and to create mount points for those plugins.
- volman code does not require write access to volman.driver_paths
=> Merge Wip 159532103

packages/rep/spec, packages/rep_windows/spec
Hi Diego Team!
This PR bumps a few submodules to support CSI spec v0.3.0. It's worth pointing out that one of those is protobuf. We have run all the unit tests and inigo successfully, so we think that everything should be good to go.
Let us know if you have any questions.
@paulcwarren and Dave
=> Update for CSI v0.3.0 Specification Changes

scripts/run-inigo
Without this change, `run-inigo` fails compilation checks because some modules don't compile for Darwin.  This change causes go to explicitly cross compile for linux.
=> Make it possible to invoke scripts/run-inigo from a Mac

CONTRIBUTING.md
The anchor tag right next to the '###' marker was preventing the header from being rendered properly.
=> Fix header rendering in CONTRIBUTING.md

jobs/rep/templates/rep.json.erb, jobs/rep/templates/rep_ctl.erb, jobs/rep/templates/setup_mounted_data_dirs.erb, jobs/rep_windows/templates/pre-start.ps1.erb, jobs/rep_windows/templates/rep.json.erb
Currently garden does not work when rootless and bpm are enabled because:
* on start we mount /var/vcap/data/rep/shared_data in the garden bpm container
* on container creation, garden (being run as a non-root user) tries to read from `/var/vcap/data/rep/shared_data/instance_identity`, but does not manage to since `/var/vcap/data/rep/shared_data` has `0700` permission and is owned by vcap
Our current approach to work around this problem is the following:
* have `/var/vcap/data/shared` owned by vcap and 0700 persmission so the data in there is still secured
* have a nested directory `vcap/vcap/data/shared/garden` which is a shared bind mount, which gets mounted in the garden bpm container. Since `/var/vcap/data/shared` does not get mounted in the container, that folder will result with …
=> Make possible for garden to access shared data in rootless

.gitmodules
I'm guessing this was an old submodule and they are always fiddly to clear :)
It is currently breaking Garden's pipeline (`error: pathspec 'src/github.com/paulcwarren/spec' did not match any file(s) known to git.`) since Concourse's git resource has [started being more precise](https://github.com/concourse/git-resource/blob/master/assets/in#L133-L153) about the submodule paths they init.
=> Remove dead submodule path

jobs/auctioneer/templates/indicators.yml.erb, jobs/bbs/templates/indicators.yml.erb, jobs/locket/templates/indicators.yml.erb, jobs/rep/templates/indicators.yml.erb, jobs/rep_windows/templates/indicators.yml.erb, jobs/route_emitter/templates/indicators.yml.erb, jobs/route_emitter_windows/templates/indicators.yml.erb
Signed-off-by: Julian Zucker <jzucker@pivotal.io>
Updates the Indicator Document to apiVersion indicatorprotocol.io/v1. This makes the document Kubernetes-compatible, and ensures the document will be usable in the 1.0.0 release of Indicator Protocol, as v0 is deprecated.
We also added a `component` key to metadata to ensure that documents for different jobs don't overwrite each other.
=> Update indicator documents to v1 and add component to metadata

.gitmodules, packages/bbs/spec, packages/benchmark-bbs/spec, packages/locket/spec
The pq library is in maintainance mode according ot the repository's
[README](https://github.com/lib/pq/tree/f3b22b2cad9e4567803b7ffd9853b8acda021438).
> This package is effectively in maintenance mode and is not actively
> developed. Small patches and features are only rarely reviewed and merged. We
> recommend using pgx which is actively maintained.
Component PRs:
- cloudfoundry/bbs#41
- cloudfoundry/locket#10
- cloudfoundry/benchmarkbbs#4
- cloudfoundry/inigo#22
=> Use jackc/pgx instead of lib/pq

packages/diego-sshd/spec, packages/route_emitter/spec, packages/route_emitter_windows/spec, packages/ssh_proxy/spec
After bumping to Go 1.14.x we missed bumping the golang/x submodules to the latest. This will bump (crypto, net, sys, text, time, and tools ) to the latest 1.14 released branch.
=> Bump golang/x package to latest release-1.14

CONTRIBUTING.md
Consul 0.7.0 segfaults on OSX
```
No future change is possible.  Bailing out early after 0.010s.
Expected
<int>: 139
to match exit code:
<int>: 0
/Users/scottschulthess/workspace/diego-release/src/code.cloudfoundry.org/consuladapter/consulrunner/clusterrunner.go:81
```
```
➜  diego-release git:(develop) ✗ consul --version
[1]    36334 segmentation fault  consul --version
```
Consul 0.7.1 works
```
➜  diego-release git:(develop) ✗ consul --version
Consul v0.7.1
```
Fixes 
#548 
Thank you!
=> Update contribution instructions to use consul 0.7.1

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [0717f49fef0dac3818cd7cdc52bf18e0ae1f7a2c-1.16.1]("https://github.com/envoyproxy/envoy/commit/0717f49fef0dac3818cd7cdc52bf18e0ae1f7a2c-1.16.1") to [e98e41a8e168af7acae8079fc0cd68155f699aa3-1.16.2]("https://github.com/envoyproxy/envoy/commit/e98e41a8e168af7acae8079fc0cd68155f699aa3-1.16.2")
=> Bump envoy to e98e41a8e1

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [e98e41a8e168af7acae8079fc0cd68155f699aa3-1.16.2]("https://github.com/envoyproxy/envoy/commit/e98e41a8e168af7acae8079fc0cd68155f699aa3-1.16.2") to [c4b7ab805f238206d8b806e12cedb9420e5d936a-1.16.3]("https://github.com/envoyproxy/envoy/commit/c4b7ab805f238206d8b806e12cedb9420e5d936a-1.16.3")
=> Bump envoy to c4b7ab805f

config/blobs.yml, packages/proxy/packaging, packages/proxy/spec
Bump envoy from [c4b7ab805f238206d8b806e12cedb9420e5d936a-1.16.3]("https://github.com/envoyproxy/envoy/commit/c4b7ab805f238206d8b806e12cedb9420e5d936a-1.16.3") to [bf5d0eb44b781ac26ff1513700bcb114b7cf4300-1.16.4]("https://github.com/envoyproxy/envoy/commit/bf5d0eb44b781ac26ff1513700bcb114b7cf4300-1.16.4")
=> Bump envoy to bf5d0eb44b

jobs/rep_windows/spec
In windows, the CPU share range is: 1 to 10000
https://github.com/Microsoft/hcsshim/blob/b144c605002d4086146ca1c15c79e56bfaadc2a7/interface.go#L77
> Please link the issue you created above for a bug or enhancement.
Thank you!
=> Update container_max_cpu_shares default in rep_windows from 1024 to 10000

docs/envoy-proxy-configuration.md, jobs/rep/spec, jobs/rep/templates/rep.json.erb, jobs/rep_windows/spec, jobs/rep_windows/templates/rep.json.erb
https://github.com/cloudfoundry/diego-release/issues/592
Root issue: cloudfoundry/routing-release#200
Thank you!
=> Add manifest property for Envoy proxy HTTP/2

jobs/auctioneer/templates/auctioneer.json.erb, jobs/bbs/templates/bbs.json.erb, jobs/file_server/templates/file_server.json.erb, jobs/locket/templates/locket.json.erb, jobs/rep/templates/rep.json.erb, jobs/rep_windows/templates/rep.json.erb, jobs/route_emitter/templates/route_emitter.json.erb, jobs/route_emitter_windows/templates/route_emitter.json.erb, jobs/ssh_proxy/templates/ssh_proxy.json.erb
Guards against operators specifying IP addresses that now fail to parse after diego components have been compiled with go 1.17.
=> add template rendering checks for ips with leading zeros for diego jobs

docs/deprecations.md
They have been superceded by the `.r1` versions
https://github.com/cloudfoundry/diego-release/issues/588
https://github.com/cloudfoundry/diego-release/issues/587
Thank you!
=> Deprecate start and evacuate_running endpoints
